"""Initial migration

Revision ID: a5593a6f33da
Revises: 
Create Date: 2023-06-02 17:32:59.169587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5593a6f33da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'students',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'])
    )

    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'teachers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'subjects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('teacher_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'])
    )

    op.create_table(
        'grades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=True),
        sa.Column('subject_id', sa.Integer(), nullable=True),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['student_id'], ['students.id']),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'])
    )

    op.create_foreign_key('fk_students_groups', 'students', 'groups', ['group_id'], ['id'])
    op.create_foreign_key('fk_subjects_teachers', 'subjects', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key('fk_grades_students', 'grades', 'students', ['student_id'], ['id'])
    op.create_foreign_key('fk_grades_subjects', 'grades', 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('fk_grades_subjects', 'grades', type_='foreignkey')
    op.drop_constraint('fk_grades_students', 'grades', type_='foreignkey')
    op.drop_constraint('fk_subjects_teachers', 'subjects', type_='foreignkey')
    op.drop_constraint('fk_students_groups', 'students', type_='foreignkey')

    op.drop_table('grades')
    op.drop_table('subjects')
    op.drop_table('teachers')
    op.drop_table('groups')
    op.drop_table('students')

    # ### end Alembic commands ###
