"""second

Revision ID: b36b63f6ce40
Revises: a5593a6f33da
Create Date: 2023-06-02 18:17:03.580723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36b63f6ce40'
down_revision = 'a5593a6f33da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
