"""third

Revision ID: de82a9e976a4
Revises: b36b63f6ce40
Create Date: 2023-06-02 18:21:53.389970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de82a9e976a4'
down_revision = 'b36b63f6ce40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
